import { EnvexProvider } from '@daniel-rose/envex'
import { EnvScript } from '@daniel-rose/envex/script'
import { getEnvByName, getPublicEnv } from '@daniel-rose/envex/server'
import type { Metadata } from 'next'
import { ReactNode } from 'react'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  const initialEnv = await getPublicEnv()
  const barEnv = await getEnvByName('BAR')

  return (
    <html lang='en'>
      <body>
        <EnvScript />
        <EnvexProvider initialEnv={initialEnv}>
          <div data-testid='server-env'>BAR: {barEnv}</div>
          {children}
        </EnvexProvider>
      </body>
    </html>
  )
}
